# -*- coding: utf-8 -*-
"""Caminhos centralizados do pipeline de analise BIM."""

PASTA_MODELOS = u"X:/06_COMPARTILHADOS DE PROJETOS/ARQUITETURA/DIEGO/TEMPLATE_LIMPEZA/ANALISE VIEW TEMPLATES EM USO/MODELOS ATIVOS"

PASTA_SAIDA = u"X:/06_COMPARTILHADOS DE PROJETOS/ARQUITETURA/DIEGO/TEMPLATE_LIMPEZA/ANALISE VIEW TEMPLATES EM USO/_RESULTADOS"

PLANILHA_AUDIT = u"X:/06_COMPARTILHADOS DE PROJETOS/ARQUITETURA/DIEGO/TEMPLATE_LIMPEZA/ANALISE VIEW TEMPLATES EM USO/01-AUDIT-BIM.xlsx"

LOG_BATCH = PASTA_SAIDA + u"/batch.log"
XLSX_DASH = PASTA_SAIDA + u"/dashboard_bim.xlsx"
